# usage:
# <p truncate-text="100">some text</p>

'use strict'

angular.module('app').directive 'truncateText', ->
  {
  restrict: 'A'
  link: ($scope, element, attrs) ->
# http://stackoverflow.com/questions/17138868/how-to-trigger-a-directive-when-updating-a-model-in-angularjs
    $scope.$watch 'someValue', (value) ->
      len = parseInt(attrs.truncateText)
      text = element.text().trim()
      trunc = undefined
      if text.length > len
        trunc = text.substring(0, len) + ' ...'
      element.text trunc
      return
    return

  }

# ---
# generated by js2coffee 2.1.0